name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

permissions:
  id-token: write  # Required for OpenID Connect (OIDC)
  contents: read   # Allows reading the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials from OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::145059604472:role/github-to-s3
        aws-region: us-east-2

    - name: Sync files to S3
      run: |
        aws s3 sync website-aws s3://mytestgithub/ --delete
