name: Sync to S3

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete

        env:
          AWS_REGION: 'us-east-2' # Optional: use GitHub secret for region if desired
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          SOURCE_DIR: 'website-aws'
          AWS_S3_BUCKET: 'mytestgithub'
